name: Go Build and Test

on:
     push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Set up Go
              uses: actions/setup-go@v2
              with:
                go-version: '1.23' 
            - name: Build
              run: go build -ldflags="-s -w" ./...
            - name: Test
              run: go test ./...